
export const backUrl = 'localhost:3000'

export const TYPES = {
    CATEGORY: 'CATEGORY',
    EXIGENCE: 'EXIGENCE',
    RELATION: 'RELATION',
}

export const CATEGORY_TYPES = {
    BEHAVIOR: 'BEHAVIOR',
    COMPONENT: 'COMPONENT',
    CONSTRAINT: 'CONSTRAINT',
    GOAL: 'GOAL',
    LACK: 'LACK',
    LIMIT: 'LIMIT',
    META_REQUIREMENT: 'META_REQUIREMENT',
    PRODUCT: 'PRODUCT',
    TASK: 'TASK',
}

export const RELATION_TYPES = {
    DISJOINS: 'DISJOINS',
    BELONGS: 'BELONGS',
    REPEATS: 'REPEATS',
    CONTRADICTS: 'CONTRADICTS',
    EXTENDS: 'EXTENDS',
    CONSTRAINTS: 'CONSTRAINTS',
    CHARACTERIZES: 'CHARACTERIZES',
}
