version: "2"
services:
  back:
    container_name: back
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo:mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
